services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'prueba'
      POSTGRES_DB: 'pilar'
    container_name: pilardb
    volumes:
      - ./postgres:/var/lib/postgresql/data